version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: modipix_backend
    env_file:
      - ./backend/.env.development.local
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src        # Mounts source code for live editing
      - ./backend/uploads:/app/uploads # Keeps uploads persistent
      - ./backend/temp:/app/temp      # Keeps temp files persistent
      - /app/node_modules             # Prevents overwriting node_modules inside container
    depends_on:
      - moderation_service

  moderation_service:
    build:
      context: ./modipix-microservice  # this must match the folder where Dockerfile and requirements.txt are
      dockerfile: Dockerfile.microservice
    container_name: modipix_moderation
    env_file:
      - ./modipix-microservice/.env.development.local
    ports:
      - "8000:8000"
    volumes:
      - ./modipix-microservice:/app
